AWS SDK v3 Support
compwright/aws-elasticsearch-connector pull request #34
Opened 2022-04-26 14:23 UTC by jamesrenaud

Addresses #32 and #33 

Adds a little bit of logic to support both the aws-sdk v2 global configuration model, and allow for use within the aws-sdk v3 which no longer uses global configuration.

Implementors using the aw-sdk v3 can simply pass `region` and a `credentials` object directly in place of the global `awsConfig`.

Added an example using the `@aws-sdk/client-sts` to the documentation, `aws4` wants the `secretAccessKey`, `accessKeyId` and `sessionToken` in `camelCase`, but all the aws-sdk v3 clients provide them in `PascalCase`, so you need to convert the properties around first - otherwise you could directly use any of the methods from `@aws-sdk/credential-providers`. This is an aws-sdk v3 backward compatibility problem, not necessarily a problem with `aws4` or this package.

2022-05-16 13:46 UTC, jamesrenaud commented
@compwright FYI

2022-05-16 14:46 UTC, compwright requested changes
@jamesrenaud thanks so much! Not sure how I missed this pull request. One minor fix needed in the readme before I can merge and release this.

2022-05-16 14:46 UTC, compwright commented on README.md
> +    "arn:aws:iam::062437324875:role/Administrator",
I don't think it's safe to include this ARN which contains your AWS ID here in the example. Please change it to an obviously fake number, or better, demonstrate in the example obtaining this from a source that is safe for storing secrets.

2022-05-16 18:46 UTC, merged

2022-05-16 18:50 UTC, jamesrenaud commented on README.md
> +    "arn:aws:iam::062437324875:role/Administrator",
Thanks for the catch, missed it in my docs sweep to make sure I didn't copy/paste anything. Better safe than sorry with AWS Account IDs

2022-05-16 19:00 UTC, jamesrenaud commented
If anyone comes digging, there's an easier way to achieve the credentials as well - I did it a little roundabout in the documentation. You can avoid the additional `AssumeRole` method by using the built-in credentials provider:

```javascript
const { fromTemporaryCredentials } = require("@aws-sdk/credential-providers");
const { Client } = require("@elastic/elasticsearch");
const createAwsElasticsearchConnector = require("./src/index.js");

async function ping() {
  const creds = await fromTemporaryCredentials({
        params: {
            RoleArn: 'arn:aws:iam::0123456789012:role/SomeRoleName',
            RoleSessionName: 'some-session',
            DurationSeconds: 3600
        }
    })();
  const client = new Client({
    ...createAwsElasticsearchConnector({
      region: "us-east-1",
      credentials: creds,
    }),
    node: "https://my-elasticsearch-cluster.us-east-1.es.amazonaws.com",
  });
  const response = await client.ping();
  console.log(`Got Response`, response);
}
```

2022-05-25 02:29 UTC, nuggie commented
hi @jamesrenaud 

I have problems using the credential-providers because the createAwsElasticsearchConnector is calling getCredentials() on the awsConfig object (which in case of credential provider is a simple json)

do you have any suggestions?